import Head from 'next/head';
import {useRouter} from 'next/router';
import Link from 'next/link';
import Image from 'next/image';
import cx from 'classnames';
import Landing from 'layouts/Landing';
import Section from 'components/ui/Section';
import BlockContent from '@sanity/block-content-to-react';
import {getCocktailData, getCocktailsList, urlForImage} from 'lib/sanity/groq';

export default function Cocktail({cocktailData}) {
  const router = useRouter()
  const {locale} = router;
  return (
    <Landing>
      {cocktailData && (
        <>
          {cocktailData.map((data) => (
            <>
              <Head key={data._id}>
                {locale === "en" && <title>{data.SEOTitle.en}</title>}
                {locale === "es" && <title>{data.SEOTitle.es}</title>}
                <meta name="description" content="Generated by create next app" />
              </Head>
              <Section className="mt-28 lg:mt-36 py-16 sm:py-20 md:py-28 lg:py-36">
                <Section.Content>
                  <div className="flex flex-col md:flex-row-reverse md:justify-between">
                    <div className="md:w-1/2 flex flex-col md:items-start">
                      <div className="prose prose-xl text-center md:text-left">
                        <h1 className="title-4xl-7xl leading-none">
                          {locale === "en" && <>{data.cocktailName.en}</>}
                          {locale === "es" && <>{data.cocktailName.es}</>}
                        </h1>
                        {locale === "en" && <BlockContent blocks={data.cocktailBlurb.en} />}
                        {locale === "es" && <BlockContent blocks={data.cocktailBlurb.es} />}
                      </div>
                      <div className="my-8 text-center md:text-left">
                        {locale === "en" && <BlockContent blocks={data.cocktailDescription.en} />}
                        {locale === "es" && <BlockContent blocks={data.cocktailDescription.es} />}
                      </div>
                    </div>
                    <div className="md:w-5/12 relative overflow-hidden h-120 mt-20 md:mt-0">
                      <Image
                        src={urlForImage(data.mainImage).url()}
                        alt="lol"
                        layout="fill"
                        objectFit="cover"
                      />
                    </div>
                  </div>
                </Section.Content>
              </Section>
            </>
          ))}
        </>
      )}
    </Landing>
  )
}

export async function getStaticProps({params}) {
  const cocktailData = await getCocktailData(params.slug);
  return {
    props: {
      cocktailData
    },
    revalidate: 1,
  };
}

export async function getStaticPaths() {
  const cocktails = await getCocktailsList();
  const paths = cocktails?.map((cocktail) => ({
    params: {
      slug: cocktail.slug,
    },
  }));
  return {
    paths,
    fallback: true,
  };
}
